### ISSUE TITLE
UWP CalendarDatePicker control doesn't show placeholder when date is null

### ISSUE THREAD

**Issue by codergrl** [Esri/data-collection-dotnet#24]
The current `CalendarDatePicker` control in UWP does not show placeholder text if the date is null. Instead it shows the current date minus 100 years. This isn't ideal for the current app. This requires further investigation. 
Potential ways to show `Placeholder` text:
- change the binding to an `x:Bind` which does not seem to work due to the `Two Way` mode
- create a custom control
- edit style of current control

Current workaround implemented:
```csharp
        private void CalendarDatePicker_Loaded(object sender, RoutedEventArgs e)
        {
            var datePicker = sender as CalendarDatePicker;
            if (datePicker.Date == datePicker.MinDate)
                datePicker.Date = null;
        }
```

**Comment by nCastle1** [comment]
This is a UWP bug: https://stackoverflow.com/questions/39775527/calendardatepicker-binding-null-value

Changing to x:Bind causes all sorts of problems, so marking this blocked.

**Comment by nCastle1** [comment]
Looking into the x:Bind problems, it appears related to the following flow:

1. User presses 'save', which closes the editing session on the popup manager
2. Relationships are updated; each call to `arcgisFeature.RelateFeature` causes the feature's properties to be updated
3. Refreshing the properties changes the value (presumably raising PCE)
4. CalendarDatePicker, with x:Bind, gets the new (old) value, and raises a DateChanged event
5. The CalendarDatePicker's value update is rejected by the popup manager, because the editing session is closed

Using regular binding does not have this issue, perhaps it is checking to ensure the value is actually changed before raising PCE while x:Bind does not?

~My next step is to try using the winUI controls; maybe they've improved the date changed behavior.~ WinUI controls don't have a date picker

**Comment by nCastle1** [comment]
[PR](https://github.com/Esri/data-collection-dotnet/pull/68)
